### ISSUE TITLE
Installation on M1 macOS

### ISSUE THREAD

**Issue by liuwei-network** [radioconda/gr-leo#1]
Hi, thanks for this great work.

Can I install this OOT on macOS?

After `sudo make install`, I still can't have gr-leo blocks in my gnuradio. I install my gnuradio via brew, with path `/opt/homebrew/bin/gnuradio-companion`. But the path of gr-leo is `/usr/local/`. How do I set DCMAKE_INSTALL_PREFIX correctly?

Thanks!

**Comment by ryanvolz** [comment]
I think you'd need to run CMake with `-DCMAKE_INSTALL_PREFIX=/opt/homebrew`. I'm not a mac user let alone homebrew, so I don't know if there's a more natural way.

By the way, the whole point of this fork is so I can package this for conda-forge, which would give you an alternative way to install this on an M1 mac: https://anaconda.org/ryanvolz/gnuradio-leo. See https://wiki.gnuradio.org/index.php/CondaInstall for more general info on using GNU Radio with conda, or check out https://github.com/ryanvolz/radioconda.

**Comment by liuwei-network** [comment]
Hi, @ryanvolz, thanks a lot!
I successfully installed gr-leo on Mac, it's so convenient with conda.
But I found some missing blocks and errors in `update_leo.grc`and `update_leo_nogui.grc`. Is it because I still need to install other OOTs? Or is gr-leo still under development?
<img width="381" alt="image" src="https://user-images.githubusercontent.com/38338565/211736512-c39f435f-15a5-46ff-8948-4d11bc9513a5.png">

**Comment by liuwei-network** [comment]
I found it, but the installation failed, gr-satnogs seems to be installed only in gnu3. 8, gr-leo works on 3.9 and above. How did you handle it, and what is the role of gr-satnogs in the example?

**Comment by ryanvolz** [comment]
Right, so gr-leo and gr-satnogs are both projects of the [Libre Space Foundation](https://libre.space/) with their original git repos here: https://gitlab.com/librespacefoundation. This fork is just where I'm keeping the changes necessary to build conda package for gr-leo, and otherwise I'm not a developer of gr-leo or gr-satnogs. As you've found, I have not packaged gr-satnogs for conda, mostly because it hasn't been updated upstream to support GNU Radio 3.10 yet. It looks like someone is working on it though: https://gitlab.com/librespacefoundation/satnogs/gr-satnogs/-/merge_requests/300. You could perhaps try building from that branch, although I'm guessing there will be issues still.

As for that example, it seems to use some of the packet encoding blocks provided by gr-satnogs. IF that's what you're after, then you'll need it. Otherwise gr-leo should be usable on its own.

**Comment by liuwei-network** [comment]
Thank you so much for your reply, very useful information!
